function Constants(){
}

Constants.prototype.DISCOVERY_PORT = 41234;
Constants.prototype.COMMUNICATION_PORT = 41232;

Constants.prototype.BLUBBLE_PHOTO_UPDATE_EVENT = 'BLUBBLE_PHOTO_UPDATE_EVENT';
Constants.prototype.BLUBBLE_MESSAGE_RECEIVED_EVENT = 'BLUBBLE_MESSAGE_RECEIVED_EVENT';

Constants.prototype.BLUBBLE_PHOTO_REQUEST_MESSAGE = 'BLUBBLE_PHOTO_REQUEST_MESSAGE';
Constants.prototype.BLUBBLE_PHOTO_UPDATE_MESSAGE = 'BLUBBLE_PHOTO_UPDATE_MESSAGE';
Constants.prototype.BLUBBLE_MESSAGE = 'BLUBBLE_MESSAGE';


module.exports = Constants;